# Exploration des sessions

In [1]:
import warnings
warnings.filterwarnings("ignore")
from allensdk.brain_observatory.ecephys.ecephys_project_cache import EcephysProjectCache

In [2]:
cache = EcephysProjectCache.from_warehouse(manifest="./data/manifest.json")
sessions = cache.get_session_table()
sessions.head(5)

,published_at,specimen_id,session_type,age_in_days,sex,full_genotype,unit_count,channel_count,probe_count,ecephys_structure_acronyms
id,,,,,,,,,,
715093703,2019-10-03T00:00:00Z,699733581,brain_observatory_1.1,118.0,M,Sst-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,884,2219,6,"[CA1, VISrl, nan, PO, LP, LGd, CA3, DG, VISl, ..."
719161530,2019-10-03T00:00:00Z,703279284,brain_observatory_1.1,122.0,M,Sst-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,755,2214,6,"[TH, Eth, APN, POL, LP, DG, CA1, VISpm, nan, N..."
721123822,2019-10-03T00:00:00Z,707296982,brain_observatory_1.1,125.0,M,Pvalb-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,444,2229,6,"[MB, SCig, PPT, NOT, DG, CA1, VISam, nan, LP, ..."
732592105,2019-10-03T00:00:00Z,717038288,brain_observatory_1.1,100.0,M,wt/wt,824,1847,5,"[grey, VISpm, nan, VISp, VISl, VISal, VISrl]"
737581020,2019-10-03T00:00:00Z,718643567,brain_observatory_1.1,108.0,M,wt/wt,568,2218,6,"[grey, VISmma, nan, VISpm, VISp, VISl, VISrl]"

Variables importantes : session_type, ecephys_structure_acronyms, full_genotype, age_in_days, sex

On sait qu'on ne regarde que les sessions du type brain_observatory_1.1

In [3]:
sessions_keep = sessions.query("session_type=='brain_observatory_1.1'").copy()

## Sessions par ecephys_structure

In [4]:
sessions_keep.ecephys_structure_acronyms.value_counts(dropna=False)

[CA1, VISrl, nan, PO, LP, LGd, CA3, DG, VISl, PoT, VISp, grey, VISpm, APN, MB, VISam]                                                1
[TH, Eth, APN, POL, LP, DG, CA1, VISpm, nan, NOT, MB, SUB, VISp, VISam, grey, VL, CA3, CA2, VISl, PO, VPM, LGd, VISal, VISrl]        1
[APN, TH, Eth, LP, DG, HPF, CA3, CA1, VISrl, nan, LGv, CA2, VISal, VISl, ProS, SUB, VISp, VISam, MB, NOT]                            1
[PPT, MB, APN, NOT, HPF, ProS, CA1, VISam, nan, POL, LP, DG, VISrl, ZI, IntG, IGL, CA3, VISal, CA2, VISl, SUB, VISp, VISpm]          1
[APN, DG, CA1, VISam, nan, LP, TH, VISpm, POL, VISrl, CA3, CA2, VISl, LGd, ProS, SUB, VISp, ZI, LGv, VISal]                          1
[PPT, NOT, SUB, ProS, CA1, VISam, nan, APN, DG, VISmmp, MB, SCig, HPF, POST, VISp, CA3, CA2, VISal, MGv, MGd, TH, VISrl]             1
[CA3, CA2, CA1, VISl, nan, APN, MB, DG, VISam, Eth, TH, LP, POL, LGd, VISp, ZI, LGv, VIS, VISrl]                                     1
[MB, APN, NOT, DG, CA1, VISam, nan, VISrl, LGv, CA3, VIS, SGN, LP, POST, SUB, VISp, PPT, HPF, ProS, VISmmp]                          1
[grey, VISal, nan, VISl, VISp, VIS, VISam]                                                                                           1
[grey, CA3, CA2, CA1, VISal, nan, LGd, HPF, DG, VISp, TH, Eth, LP, VISpm, APN, MB, VISrl, POL, ZI, LGv, IGL]                         1
[grey, VISrl, nan, VISal, VISp, VISpm, VISam]                                                                                        1
[MB, TH, PP, PIL, DG, CA3, CA1, VISal, nan, grey, CA2, VISl, LGd, VISp, LP, VISpm, APN, VISam]                                       1
[MB, SCig, PPT, NOT, SUB, ProS, CA1, VISam, nan, MGm, MGv, TH, LGd, CA3, DG, VISal, APN, VISp, POL, VISpm]                           1
[MGv, MGd, TH, DG, CA1, VISal, nan, SGN, LP, SUB, VISp, APN, MB, VISpm, PPT, OP, NOT, HPF, ProS, VISam]                              1
[grey, DG, CA3, CA1, VISli, nan, MGd, SGN, LP, TH, ProS, VISp, VISrl, VPM, LGd, VISal, MRN, MB, PPT, OP, NOT, SUB, VISam]            1
[LP, DG, CA3, CA1, VISrl, nan, PO, LGd, HPF, VISal, TH, LGv, VISl, MGm, SGN, ProS, SUB, VISp, Eth, APN, VIS, MRN, MB, NOT, VISam]    1
[TH, DG, CA3, CA1, VISl, nan, PO, Eth, LP, VISpm, VISrl, VPM, LGd, CA2, VISal, POL, APN, MB, SCig, POST, SUB, VISp, VISam]           1
[grey, VISrl, nan, MGv, MGd, TH, LGd, CA3, DG, CA1, VISal, VISl, APN, LP, MB, VISpm, SGN, ProS, VISp, SCig, PPT, NOT, VISam]         1
[PoT, LP, LGd, CA3, DG, CA1, VISp, nan, VPM, CA2, VISrl, PO, Eth, TH, VISpm, APN, POL, VISam]                                        1
[APN, POL, LP, DG, CA1, VISam, nan, LGd, HPF, CA3, VISpm, VISp, CA2, VISl, grey, TH, VISal, VISrl]                                   1
[grey, LGv, CA3, DG, CA1, VISl, nan, APN, POL, SGN, LP, VISrl, PO, LGd, MGm, SUB, VISp, PoT, Eth, VISpm, MB, VISam]                  1
[LP, DG, CA1, VISp, nan, LGd, CA3, VISrl, VPM, TH, CA2, VISal, LGv, IGL, VISl, PO, LD, VISpm, Eth, VISam]                            1
[grey, VISrl, nan, VISal, IntG, IGL, LGd, CA3, DG, CA1, VISl, VISp, VISpm, VISam]                                                    1
[VPM, TH, LGd, CA3, CA2, CA1, VISal, nan, grey, VISl, VISp, VISpm, VISrl]                                                            1
[Eth, TH, LP, POL, APN, DG, CA1, VIS, nan, CA3, VISrl, VPL, IGL, LGd, CA2, VISal, VISl, SGN, SUB, VISp]                              1
[LP, LGd, HPF, DG, CA3, CA1, VISrl, nan, PP, PIL, TH, MGv, VISl, ProS, SUB, VISp, PO, Eth, VISmma, APN, VISam]                       1
[VISal, nan, grey, VISl, VISrl, VISp, VISpm, VIS]                                                                                    1
[grey, VISam, nan, VIS, VISp, VISl, VISrl]                                                                                           1
[grey, VISmma, nan, VISpm, VISp, VISl, VISrl]                                                                                        1
[grey, VISpm, nan, VISp, VISl, VISal, VISrl]                                                                                         1
[MB, SCig, PPT, NOT, DG, CA1, VISam, nan, LP, VIS, ProS, VISp, LGv, CA3, VISl, APN, POL, LGd, HPF, VISal, VISrl]                     1
[APN, POL, LP, DG, CA1, VISrl, nan, LGd, CA3, VISal, CA2, VISl, ProS, SUB, VISp, VISmma, VISam, COAa]                                1
Name: ecephys_structure_acronyms, dtype: int64

Les régions les plus affectées par les static_gratings et les natural_scenes semblent être les VIS (https://observatory.brain-map.org/visualcoding/).  
Toutes les sessions brain_observatory_1.1 ciblent au moins une région VIS.  
La région la plus activée est VISp (toujours activée). Les autres importantes semblent être VISl, VISal, VISrl, VISpm et VISam.

In [5]:
sessions_keep[sessions_keep.ecephys_structure_acronyms.astype(str).str.contains("VISp")*sessions_keep.ecephys_structure_acronyms.astype(str).str.contains("VISl")*sessions_keep.ecephys_structure_acronyms.astype(str).str.contains("VISal")*sessions_keep.ecephys_structure_acronyms.astype(str).str.contains("VISrl")*sessions_keep.ecephys_structure_acronyms.astype(str).str.contains("VISpm")*sessions_keep.ecephys_structure_acronyms.astype(str).str.contains("VISam")]

,published_at,specimen_id,session_type,age_in_days,sex,full_genotype,unit_count,channel_count,probe_count,ecephys_structure_acronyms
id,,,,,,,,,,
719161530,2019-10-03T00:00:00Z,703279284,brain_observatory_1.1,122.0,M,Sst-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,755,2214,6,"[TH, Eth, APN, POL, LP, DG, CA1, VISpm, nan, N..."
750332458,2019-10-03T00:00:00Z,726141251,brain_observatory_1.1,91.0,M,wt/wt,902,2216,6,"[grey, VISrl, nan, VISal, IntG, IGL, LGd, CA3,..."
750749662,2019-10-03T00:00:00Z,726162197,brain_observatory_1.1,92.0,M,wt/wt,761,2223,6,"[LP, DG, CA1, VISp, nan, LGd, CA3, VISrl, VPM,..."
754312389,2019-10-03T00:00:00Z,719828690,brain_observatory_1.1,140.0,M,wt/wt,502,2220,6,"[APN, POL, LP, DG, CA1, VISam, nan, LGd, HPF, ..."
755434585,2019-10-03T00:00:00Z,730760270,brain_observatory_1.1,100.0,M,Vip-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,650,2220,6,"[grey, VISrl, nan, MGv, MGd, TH, LGd, CA3, DG,..."
756029989,2019-10-03T00:00:00Z,734865738,brain_observatory_1.1,96.0,M,Sst-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,684,2214,6,"[TH, DG, CA3, CA1, VISl, nan, PO, Eth, LP, VIS..."
791319847,2019-10-03T00:00:00Z,769360779,brain_observatory_1.1,116.0,M,Vip-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,555,2229,6,"[APN, DG, CA1, VISam, nan, LP, TH, VISpm, POL,..."
797828357,2019-10-03T00:00:00Z,776061251,brain_observatory_1.1,107.0,M,Pvalb-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,611,2232,6,"[PPT, MB, APN, NOT, HPF, ProS, CA1, VISam, nan..."

In [6]:
sessions_keep = sessions_keep[sessions_keep.ecephys_structure_acronyms.astype(str).str.contains("VISp")*sessions_keep.ecephys_structure_acronyms.astype(str).str.contains("VISl")*sessions_keep.ecephys_structure_acronyms.astype(str).str.contains("VISal")*sessions_keep.ecephys_structure_acronyms.astype(str).str.contains("VISrl")*sessions_keep.ecephys_structure_acronyms.astype(str).str.contains("VISpm")*sessions_keep.ecephys_structure_acronyms.astype(str).str.contains("VISam")].copy()
sessions_keep["N_STRUCTURES"] = sessions_keep.ecephys_structure_acronyms.apply(lambda x: len(x))

Que des mâles.  
Des souris au même génotype ont des âges très différents.  
Ainsi, on peut choisir un génotype et utiliser les différentes souris pour comparaison.

In [7]:
sessions_keep

,published_at,specimen_id,session_type,age_in_days,sex,full_genotype,unit_count,channel_count,probe_count,ecephys_structure_acronyms,N_STRUCTURES
id,,,,,,,,,,,
719161530,2019-10-03T00:00:00Z,703279284,brain_observatory_1.1,122.0,M,Sst-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,755,2214,6,"[TH, Eth, APN, POL, LP, DG, CA1, VISpm, nan, N...",24
750332458,2019-10-03T00:00:00Z,726141251,brain_observatory_1.1,91.0,M,wt/wt,902,2216,6,"[grey, VISrl, nan, VISal, IntG, IGL, LGd, CA3,...",14
750749662,2019-10-03T00:00:00Z,726162197,brain_observatory_1.1,92.0,M,wt/wt,761,2223,6,"[LP, DG, CA1, VISp, nan, LGd, CA3, VISrl, VPM,...",20
754312389,2019-10-03T00:00:00Z,719828690,brain_observatory_1.1,140.0,M,wt/wt,502,2220,6,"[APN, POL, LP, DG, CA1, VISam, nan, LGd, HPF, ...",18
755434585,2019-10-03T00:00:00Z,730760270,brain_observatory_1.1,100.0,M,Vip-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,650,2220,6,"[grey, VISrl, nan, MGv, MGd, TH, LGd, CA3, DG,...",23
756029989,2019-10-03T00:00:00Z,734865738,brain_observatory_1.1,96.0,M,Sst-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,684,2214,6,"[TH, DG, CA3, CA1, VISl, nan, PO, Eth, LP, VIS...",23
791319847,2019-10-03T00:00:00Z,769360779,brain_observatory_1.1,116.0,M,Vip-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,555,2229,6,"[APN, DG, CA1, VISam, nan, LP, TH, VISpm, POL,...",20
797828357,2019-10-03T00:00:00Z,776061251,brain_observatory_1.1,107.0,M,Pvalb-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,611,2232,6,"[PPT, MB, APN, NOT, HPF, ProS, CA1, VISam, nan...",23

# Téléchargement des sessions

In [ ]:
from utils import retrieve_link, download_data

In [ ]:
retrieve_link(754312389)